package net.sharetrip.flight.utils

const val ARG_SELECTED_POSITION: String = "ARG_SELECTED_POSITION"
const val ARG_RULES: String = "ARG_RULES"
const val ARG_FLIGHT_SEARCH_MODEL: String = "ARG_FLIGHT_SEARCH_MODEL"
const val ARG_ITEM_FLIGHTS: String = "ARG_ITEM_FLIGHTS"
const val ARG_RULES_DETAILS: String = "ARG_RULES_DETAILS"
const val ARG_FLIGHT_DETAILS_DATA: String = "ARG_FLIGHT_DETAILS_DATA"
const val ARG_FLIGHT_SEARCH: String = "ARG_FLIGHT_SEARCH"
const val ARG_FLIGHTS: String = "ARG_FLIGHTS"
const val ARG_DISCOUNT_MODEL: String = "ARG_DISCOUNT_MODEL"
const val ARG_COUPON_RESPONSE: String = "ARG_COUPON_RESPONSE"
const val ARA_ITEM_FLIGHTS_SEGMENT = "ARA_ITEM_FLIGHTS_SEGMENT"
const val ARA_ITEM_FLIGHTS_SEGMENT_POSITION = "ARA_ITEM_FLIGHTS_SEGMENT_POSITION"
const val ARA_ITEM_FLIGHTS_SEGMENT_DATA = "action_flightDetails_to_segment"

const val RESULT_PASSPORT_CAMERA_CODE_SELECTION = 206
const val RESULT_PASSPORT_GALLERY_CODE_SELECTION = 207
const val RESULT_VISA_CAMERA_CODE_SELECTION = 208
const val RESULT_VISA_GALLERY_CODE_SELECTION = 209
const val ARGS_COVID_ADD_ON_LIST = "COVID_ADD_ON_LIST"
const val ARGS_SELECTED_COVID_ADD_ON = "ARGS_SELECTED_COVID_ADD_ONT"
const val ARGS_TRAVEL_INSURANCE_LIST = "ARGS_TRAVEL_INSURANCE_LIST"
const val ARGS_SELECTED_TRAVEL_INSURANCE_OPTION = "ARGS_SELECTED_TRAVEL_INSURANCE_OPTION"
const val ARGS_BAGGAGE_INSURANCE_LIST = "ARGS_BAGGAGE_INSURANCE_LIST"
const val ARGS_SELECTED_BAGGAGE_INSURANCE_OPTION = "ARGS_SELECTED_BAGGAGE_INSURANCE_OPTION"
const val APPLICATION_ID = "net.sharetrip"
const val FLIGHT_DATE_PASSENGERS = "FLIGHT_DATE_PASSENGERS"
const val ARG_IMAGE_DATA = "ARG_IMAGE_DATA"

const val ARG_IMAGE_URL = "ARG_IMAGE_URL"
const val ARG_IMAGE_TAG = "ARG_IMAGE_TAG"
const val ARG_FOR_CONFIRMATION = "ARG_FOR_CONFIRMATION"

const val ARG_FLIGHT_DATA = "ARG_FLIGHT_DATA"

const val GOTO_PAYMENT = "GOTO_PAYMENT"
const val GOTO_TERMS = "GOTO_TERMS"
const val GOTO_PRIVACY = "GOTO_PRIVACY"
const val GOTO_FLIGHT_DASHBOARD = "GOTO_FLIGHT_DASHBOARD"

const val ARG_ADAPTER_POSITION = "ARG_ADAPTER_POSITION"
const val ARG_TRAVELLER_DATA = "ARG_TRAVELLER_DATA"
const val ARG_ALL_TRAVELLER = "ARG_ALL_TRAVELLER"
const val ARG_ALL_TRAVELLER_AND_DATA = "ARG_ALL_TRAVELLER_AND_DATA"


const val YOUR_VOUCHER_REQUEST_HAS_BEEN_SUCCESSFULLY_SENT = "Your voucher request has been successfully sent"
const val YOUR_BOOKING_HAS_BEEN_SUCCESSFULLY_CANCELLED = "Your booking has been successfully cancelled"
const val AIR_FARE_RULE_NOT_FOUND = "Air fare rule not found"
const val FARE_DETAILS_NOT_FOUND = "Fare details not found"
const val NETWORK_ERROR = "Network Error"

const val ARG_FLIGHT_HISTORY_RESPONSE = "ARG_FLIGHT_HISTORY_RESPONSE"
const val ARG_FLIGHT_VOID_QUOTATION = "ARG_FLIGHT_VOID_QUOTATION"

const val EXTRA_SEARCH_ID = "EXTRA_SEARCH_ID"
const val EXTRA_SEQUENCE_CODE = "EXTRA_SEQUENCE_CODE"
const val EXTRA_RULE_TYPE = "EXTRA_RULE_TYPE"
const val EXTRA_BAGGAGE_DETAILS = "EXTRA_BAGGAGE_DETAILS"
const val EXTRA_BAGGAGE_COST = "EXTRA_BAGGAGE_COST"
const val ARG_RULES_DATA = "ARG_RULES_DATA"

const val EXTRA_PRICE_BREAK_DOWN = "EXTRA_PRICE_BREAK_DOWN"

const val ARG_REFUND_VOID_DATA = "ARG_REFUND_VOID_DATA"
const val ARG_SELECTED_PASSENGERS = "ARG_SELECTED_PASSENGERS"
const val ARG_REFUND_QUOTATION_RESPONSE = "ARG_REFUND_QUOTATION_RESPONSE"

const val ARG_HISTORY_DATA = "ARG_HISTORY_DATA"

const val ARG_FLIGHT_LIST_DATA = "ARG_FLIGHT_LIST_DATA"

const val ARG_FLIGHT_SEARCH_AIRPORT = "ARG_FLIGHT_SEARCH_AIRPORT"
const val ARG_FLIGHT_SEARCH_BUNDLE = "ARG_FLIGHT_SEARCH_BUNDLE"
const val IS_ORIGIN_OR_DESTINATION = "IS_ORIGIN_OR_DESTINATION"

const val ARG_FLIGHT_SEARCH_MULTI_CITY = "ARG_FLIGHT_SEARCH_MULTI_CITY"
const val ARG_CLASS_NAME = "ARG_CLASS_NAME"


const val PLEASE_SELECT_ORIGIN_DESTINATION = "PLease select origin and destination airport."
const val GOTO_TRAVELLER = "GOTO_TRAVELLER"
const val PICK_DEPARTURE_DATE_REQUEST = "PICK_DEPARTURE_DATE_REQUEST"
const val GOTO_FLIGHT_LIST = "GOTO_FLIGHT_LIST"

const val ARG_AIRPORT_CODE = "ARG_AIRPORT_CODE"
const val ARG_AIRPORT_CITY = "ARG_AIRPORT_CITY"
const val ARG_AIRPORT_ADDRESS = "ARG_AIRPORT_ADDRESS"

